apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "deployment.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "deployment.selectorLabels" . | nindent 6 }}
